#!/usr/bin/env bash

### USAGE

# ./convertToIcns <input png> <outp icns>
# Example
# ./convertToIcns ~/sample.png ~/Desktop/converted.icns

# exit the shell script on error immediately
set -e

# Exec Paths
HAVE_IMAGEMAGICK=
HAVE_ICONUTIL=
HAVE_SIPS=

type convert &>/dev/null && HAVE_IMAGEMAGICK=true
type iconutil &>/dev/null && HAVE_ICONUTIL=true
type sips &>/dev/null && HAVE_SIPS=true

[[ -z "$HAVE_ICONUTIL" ]] && { echo >&2 "No se puede encontrar el ejecutable iconutil requerido"; exit 1; }
[[ -z "$HAVE_IMAGEMAGICK" && -z "$HAVE_SIPS" ]] && { echo >&2 "No se puede encontrar el convertidor de imágenes requerido, instale sips o imagemagick"; exit 1; }

# Parameters
SOURCE="$1"
DEST="$2"

# Check source and destination arguments
if [ -z "${SOURCE}" ]; then
	echo "No se ha especificado ninguna imagen de origen"
	exit 1
fi

if [ -z "${DEST}" ]; then
	echo "Sin destino especificado"
	exit 1
fi

TEMP_DIR="$(mktemp -d)"
ICONSET="${TEMP_DIR}/converted.iconset"

function cleanUp() {
    rm -rf "${TEMP_DIR}"
}

trap cleanUp EXIT

"${BASH_SOURCE%/*}/convertToIconset" "${SOURCE}" "${ICONSET}"

# Create an icns file lefrom the iconset
iconutil -c icns "${ICONSET}" -o "${DEST}"

trap - EXIT
cleanUp
