#!/usr/bin/env bash

# Uso

# ./convertToIco <input png or ico> <outfilename>.ico
# Ejemplo
# ./convertToPng ~/sample.png ~/converted.ico

set -e

type convert >/dev/null 2>&1 || { echo >&2 "No se puede encontrar el ejecutable ImageMagick Convert requerido"; exit 1; }

SOURCE=$1
DEST=$2

if [ -z "${SOURCE}" ]; then
	echo "No se ha especificado ninguna imagen de origen"
	exit 1
fi

if [ -z "${DEST}" ]; then
	echo "Sin destino especificado"
	exit 1
fi

NAME=$(basename "${SOURCE}")
EXT="${NAME##*.}"

if [ "${EXT}" == "ico" ]; then
    cp "${SOURCE}" "${DEST}"
    exit 0
fi

convert "${SOURCE}" -resize 256x256 "${DEST}"
